import BackButton from "../../components/common/BackButton";

export default function StandardizingHealthcareData() {
  return (
    <section className="container mx-auto px-4 py-16">
      <BackButton fallback="/offerings" />
      <div className="grid lg:grid-cols-2 gap-10 items-start mt-6">
        <img src="https://images.pexels.com/photos/7821463/pexels-photo-7821463.jpeg" alt="Standardizing healthcare data" className="rounded-xl border object-cover w-full h-72" />
        <div>
          <h1 className="text-4xl font-bold tracking-tight">Standardizing Healthcare Data</h1>
          <ul className="mt-6 space-y-3 text-sm text-muted-foreground">
            <li>Standards are important to us, as we are able to capture normalized information from each data source for use in the unified platform. All the stakeholders record, store and communicate all clinical information in a standardized format. Apart from ensuring interoperability, this system also achieves the following:</li>
            <li>Mapping of the various clinical dictionaries like ICD-10, LOINC and even catalogs like RxNorm for pharmacies. Standardizing formats for textual data, still images, motion-pictures and audio images being generated by or stored on systems and equipments.</li>
            <li>Patient data security and privacy; ensured by utilizing 3DES and Advanced Encryption Standards for encrypting the data during storage, retrieval and communications, using Transport Level Security and SSL.</li>
            <li>Standardizing the minimum data set for the various diseases not listed in the ITH framework.</li>
          </ul>
        </div>
      </div>
    </section>
  );
}
